apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-job
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocp-day2-wait-job
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: ["machineconfiguration.openshift.io"]
    resources: ["machineconfigpools"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocp-day2-wait-job
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocp-day2-wait-job
subjects:
  - kind: ServiceAccount
    name: wait-job
    namespace: openshift-gitops
