# Move the integrated image registry to infrastructure nodes.
# Docs: https://docs.redhat.com/en/documentation/openshift_container_platform/4.22/html/machine_management/creating-infrastructure-machinesets#infrastructure-moving-registry_creating-infrastructure-machinesets
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      value: reserved
