apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../07-openshift-gitops-operator/namespace.yaml
  - ../../../07-openshift-gitops-operator/operatorgroup.yaml
  - ../../../07-openshift-gitops-operator/subscription.yaml
